---
functional:
  - Форма вывода средств со счета должна быть доступна по ссылке https://groall.noda.pro/test_qa и должна быть доступна для пользователей соответствующей роли.
  - Форма должна содержать поля "Сумма", кнопку "Вывести".
  - После ввода суммы и нажатия кнопки "Вывести", должен происходить вывод указанной суммы со счета пользователя.
  - Пользователь должен быть уведомлен об успешном выводе средств после нажатия кнопки "Вывести".
non-functional:
  - Форма вывода средств должна загружаться быстро.
  - Форма должна быть простой и интуитивно понятной для пользователей.
  - Форма должна быть защищена от взлома и злоумышленников, которые пытаются получить доступ к аккаунту пользователя.
implicit:
  - Форма должна быть доступна на любых устройствах и браузерах.
  - Форма должна быть легко обновляемой и поддерживаемой.
  - Система должна быть легко масштабируемой для увеличения количества пользователей.
